### ISSUE TITLE
it's not possible to imports maps(wmflabs)

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/mapwarper#107]
just try this one:
https://commons.wikimedia.org/wiki/File:Descriptionis_Ptolemaicæ_avgmentvm_siue_Occidentis_notitia_breui_commentario_illustrata_p168.tif

**Comment by timwaters** [comment]
```
NoMethodError (undefined method `new_from_wiki' for #<Class:0x00000005295db0>):
  app/controllers/wikimaps_controller.rb:70:in `create'
```

Will fix ASAP

**Comment by timwaters** [comment]
Cause was bad git merge when merging api code and new template code :( working on fix now 

I should have run the tests after merging. Sorry!

**Comment by timwaters** [comment]
Fixed now. Apologies!

http://warper.wmflabs.org/maps/1301
