### ISSUE TITLE
502 Bad Gate way when using oauth

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/mapwarper#108]
It seams like it could be caused by the parameter `auth_origin_url` or its value:

Works but redirects to warper.wmflabs.org:

https://warper.wmflabs.org/u/auth/mediawiki

Do not work:

https://warper.wmflabs.org/u/auth/mediawiki?auth_origin_url=https://commons.wikimedia.org/wiki/File:Descriptionis_Ptolemaicæ_avgmentvm_siue_Occidentis_notitia_breui_commentario_illustrata_p182.tif

**Comment by timwaters** [comment]
Duplicate - We were discussing this in this ticket: #106

**Comment by timwaters** [comment]
leaving open, will close when fixed, but discussion to be had in #106

**Comment by timwaters** [comment]
see #106 closing, I believe the issue has been diagnosed and partially workarounded
