### ISSUE TITLE
Warper adds parameters in wrong template

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/mapwarper#113]
Found the following file where parameters added by the Warper has ended up in the wrong template([Commons](https://commons.wikimedia.org/wiki/File:A_map_of_the_town_of_Lexington_Middlesex_County,_Mass._%283855458841%29.jpg)):

```
{{Map
|title=A map of the town of Lexington Middlesex County, Mass
|author=Walling, Henry Francis
|date=1853
|source=[http://ark.digitalcommonwealth.org/ark:/50959/x059c898m Digital Commonwealth]
|location=Lexington, MA
|scale=10632
|institution={{Institution:Boston Public Library}}
|dimensions={{Size|cm| warp_status=warped
| latitude=42.394155/42.5016334
| longitude=-71.2857071/-71.1656438
|87|70}}
}}

```

**Comment by timwaters** [comment]
OKay, this looks bad. Probably due to how it parses the template text. Will get on it asap

**Comment by timwaters** [comment]
For the moment wiki editing should be disabled to reduce any harm

**Comment by timwaters** [comment]
I added config param to disable wiki editing, whilst fixing.

Now new parameters will be added at the end of the Template list, and not stuck inside the existing ones. This should be sufficient.

I've also fixed 3 wiki pages with this borked edit

**Comment by timwaters** [comment]
Thanks @Abbe98 for noticing the bug! :dancers:
