### ISSUE TITLE
Rectify tab results in 500 server error

### ISSUE THREAD

**Issue by Abbe98** [wikimaps-dev/mapwarper#115]
For this specific map:
http://warper.wmflabs.org/maps/1508

ping @puik

**Comment by puik** [comment]
This one seems to have the same problem:
https://warper.wmflabs.org/maps/1532

**Comment by timwaters** [comment]
This is due to the server running out of space. Will fix.

**Comment by timwaters** [comment]
Actually, it's not to do with the space (which has been increased) - rather its to do with an error with the best guess service YQL

**Comment by timwaters** [comment]
and live.
