### ISSUE TITLE
View unwarped

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#14]

**Comment by susannaanas** [comment]
Is this the "View original" view?

**Comment by timwaters** [comment]
Yes, an un-rectified slippy map

https://docs.google.com/presentation/d/10ICyB7rHzuQ02QGl65Zcl6I124Mb4HI9ImGjeoa3_xo/edit#slide=id.g55507fafd_00

**Comment by timwaters** [comment]
Closing this as the plan now is for mapwarper to just act as an API. 
The front end would be in another project

**Comment by timwaters** [comment]
Closing this as the plan now is for mapwarper to just act as an API. 
The front end would be in another project
