### ISSUE TITLE
View warped

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#15]

**Comment by susannaanas** [comment]
I think this is the same as the overlay view in the control point interface. Are there reasons why they should be separate? I am proposing they could be made into one. The view could be launched to full screen. 
This would be the point for additional actions, such as annotating the map, adding an information layer (thematic data, borders, routes, explanations, animations, timelines) and sampling it to a Wikimedia article (and elsewhere). Again a task for an intern or a volunteer.

**Comment by timwaters** [comment]
I would assume a public user or a logged out user would want to Browse maps and see the result of others work without working on them themselves. The Tools need to show the results of the tools.

Is it possible for a user to see a warped map without being logged in?  If so, how?
Does the warp interface have a read only mode? 

How would a user know if a map is rectified and can be viewed in that state?

How does a public user get to that page without being logged in?

What happens when it becomes full screen? What will a user see? 
Why would a user want to make it full screen?

Perhaps this "view" should be put into the View section?

**Comment by susannaanas** [comment]
I think the proposal to bundle viewing as map and viewing as warped\* sounds good. There would then be a toggle button to switch between the views?

*georeferenced: could also be only one point, when it will show as pinned, or with the rough placement, when it also shows as an overlay. In this stage _only warped_

I have created views to the flows document. This one has two login stages combined
![nayttokuva 2014-12-16 kello 22 46 45](https://cloud.githubusercontent.com/assets/4725416/5461640/83e93cde-8575-11e4-9d56-c6b148ff695b.png)

These ones have them separate

![nayttokuva 2014-12-16 kello 22 57 45](https://cloud.githubusercontent.com/assets/4725416/5461841/0f214462-8577-11e4-869a-b2c88210c242.png)

![nayttokuva 2014-12-16 kello 22 53 47](https://cloud.githubusercontent.com/assets/4725416/5461759/8c9a1e6a-8576-11e4-8296-fc821e227134.png)

Here a link to the flows doc (was a wrong link earlier)
https://docs.google.com/presentation/d/10ICyB7rHzuQ02QGl65Zcl6I124Mb4HI9ImGjeoa3_xo

**Comment by timwaters** [comment]
For this milestone, the button should should the map as georeferenced, as rough placement / pinned feature is in the backlog.

**Comment by timwaters** [comment]
Also, you can copy and paste images if they are not that big into these comments so that others can view them, thus;

![image](https://cloud.githubusercontent.com/assets/48941/5457936/479c7c52-8546-11e4-9e06-c5eb6a837dd3.png)

**Comment by susannaanas** [comment]
I had pasted the wrong link. the right one is places now

**Comment by timwaters** [comment]
Closing this as the plan now is for mapwarper to just act as an API. 
The front end would be in another project
