### ISSUE TITLE
Allow users to add custom map tiles for rectification

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#33]
Including:
-  OHM tiles

May want to do via white list?

**Comment by susannaanas** [comment]
Some WMS resources that could be used:
- [Kartdata NIB, Norway: bitmap](https://kartkatalog.geonorge.no/metadata/kartverket/kartdata-nib/cfbac836-7892-4b30-a49e-7b555e503656) CC BY 4.0
- [FKB2 WMS, Base map, Norway](https://kartkatalog.geonorge.no/metadata/kartverket/fkb2-wms/11202386-1edd-48cf-b3fb-99c36b64dec3) CC BY 4.0
- [GEBCO skyggerelief WMS, Norway](https://kartkatalog.geonorge.no/metadata/kartverket/gebco-skyggerelief-wms/25549b7e-53e2-4493-bb9f-2a708fd5d9bb) PD?
- [Sjøkart raster WMS, Norawy](https://kartkatalog.geonorge.no/metadata/kartverket/sjokart-raster-wms/e76d4a94-ea03-41c4-b2d9-493fad5b0a43) PD?

**Comment by Abbe98** [comment]
This is something that should be done in Warper clients.

Relevant list of imagery:
https://github.com/OpenHistoricalMap/iD/blob/master/data/imagery.json

**Comment by timwaters** [comment]
Added control button to the map panel in the warp page.
Users can add in Tiles in the Z/X/Y format in any image .gif, png, jpg formats etc Similar to iD behaviour. Z/X/Y have to be in the same order

Limitations  - Missing - subdomains, {u} or {g} and the ZXY params being in a different order 

Examples acceptable formats

```
https://maps.wikimedia.org/osm/{z}/{x}/{y}.png
https://maps.wikimedia.org/osm/10/507/329.png
http://c.tile.openstreetmap.org/{z}/{x}/{y}.png
http://c.tile.openstreetmap.org/10/507/329.png
```

![screenshot - 050716 - 14 51 47](https://cloud.githubusercontent.com/assets/48941/16586994/6e25cad4-42c0-11e6-936f-87a0f0618d28.png)
![screenshot - 050716 - 14 52 45](https://cloud.githubusercontent.com/assets/48941/16586993/6e2368de-42c0-11e6-91ba-8984716a2aa4.png)
![screenshot - 050716 - 14 53 07](https://cloud.githubusercontent.com/assets/48941/16586992/6e01f5fa-42c0-11e6-9a2f-677fe2f65963.png)

**Comment by susannaanas** [comment]
It's awesome that it's there!! I have a base map that was really difficult to show in iD. I had to add an unexplained minus sign to the url and it started working. Now I am trying to use the same link for the Warper, and no luck. Here is a link that works in iD: http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/hel%3Aorto1932@EPSG%3A900913@png/{zoom}/{x}/{-y}.png

The image covers Helsinki.

The more I try the more rows I get in the dialog. Should the older ones be removed?

![nayttokuva 2016-08-04 kello 15 12 11](https://cloud.githubusercontent.com/assets/4725416/17401375/fdf584d6-5a55-11e6-8707-a4663b7ee0a2.png)

**Comment by timwaters** [comment]
It would need to be `{z}/{x}/{y}`

negative values `{-y}` are not currently supported 

http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/hel%3Aorto1932@EPSG%3A900913@png/{z}/{x}/{-y}.png
