### ISSUE TITLE
warper updates commons filepage, warped, bounding box etc

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#45]
for map template

warped

help_warp

and the bounding box

**Comment by timwaters** [comment]
if there is a Map template:
if the map is warped and there is just help_warp - add warped=yes

if there is warped=no change it to warped=yes

add the latitude and longitude

save the change as the wiki user or if not logged in, as a designated wiki bot user.

**Comment by susannaanas** [comment]
Related issue in maptemplate. Suggestion to use a single parameter.

https://github.com/wikimaps-dev/maptemplate/issues/1

**Comment by timwaters** [comment]
closing this issue as it was closed in previous milestone. WIll make new issue for new feature
