### ISSUE TITLE
Mosaic export

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#56]
Reported over mail:
I have been looking at the project workflow, in terms of what I hope to get out of the warper. It seems like Wikimaps Warper Mosaics aren’t the same as MapWarper Layers, in terms of allowing me to generate a single TMS from a series of maps. 

In MapWarper, under the export tab for Layers, you can generate this: 
Tiles (Google/OSM scheme): http://mapwarper.net/layers/tile/428/{z}/{x}/{y}.png 

But in Wikimaps, the export tab for Mosaics has the same structure as for individual maps: 
Tiles (Google/OSM scheme): http://warper.wmflabs.org/maps/tile/274/{z}/{x}/{y}.png

One of the goals of using a browser-based warper was to be able to generate a single TMS from the 174 maps that I could pull into a Task Manager (which requires a single link, in order to overlay the maps). Will I still be able to do this with the Wikimaps Warper? 

Answered:
We have only renamed things in Wikimaps Warper, layer=mosaic. We disabled layers/mosaics for some time to simplify the process. We have brought them in again and created these new features.

**Comment by timwaters** [comment]
Different structure from maps.

![screenshot from 2015-12-10 13 11 14](https://cloud.githubusercontent.com/assets/48941/11716128/852e7444-9f3f-11e5-8071-01732862f56f.png)
