### ISSUE TITLE
Wikimaps actions = API functionalities?

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#62]
1. Import maps
   - List imports
   - Sort imports
   - Batch import a map category from Commons
     - Create a mosaic
     - Re-import/edit a map category
   - Import a single map from Commons
2. Find maps
   - Find textual
   - Find using the map / by typed location
   - List maps / mosaics
   - Display maps / mosaics on map
3. Map actions
   1. Select base map
      - OSM / WMF Maps
      - Open WMS resources filtered by location
   2. Georeference
      - Control point interface
        1. Points
           - Add point (click)
           - Add second point (click & confirm)
           - Move point (drag point, when adding or later selecting)
             - Add coordinates
             - Add address or location
             - Show lens on drag
           - Submit point pair
        2. Map controls
           - Move/zoom map
           - Lock maps together
           - Change base map
           - Show/hide map overlay
           - Change transparency of overlay
           - Editing control points in overlay mode
             - Show lens on drag, reveals underlying layer
      - Control point table
        1. Edit control point manually
        2. Add control point manually
        3. Delete point
        4. Import points
        5. Export points
        6. Toggle table visibility
      - Settings
        - Change rectification settings
        - Change interpolation settings
        - Clipping mask options
   3. Crop
      - Points
        1. Add points
        2. Edit points
        3. Delete points
        4. Delete mask
      - Image control
        1. Pan
        2. Zoom
      - Toggle visibility
   4. Preview
      - Map controls
      - Transparency control
   5. Trace
      - Embed OHM
   6. Export
      - GeoTIFF, PNG, KML, WMS, tiles, pointcsv
4. Mosaic actions
   - Show mosaic on map
   - List maps
   - Delete mosaic
   - Toggle visibility
   - Merge
   - Export
     - KML, WMS, tiles
5. Admin actions
   - List activity
   - Imports (see imports)
   - User stats
     - List user stats
     - Sort list
       - View user stats
       - View details
   - Administer users
     - List users
     - Delete user
     - Disable user
     - Edit roles
6. User
   - View user stats
   - List user uploaded maps

**Comment by timwaters** [comment]
Thanks. This is planning or documentation and could live elsewhere than in these issues list (hackpad, wiki, gdocs etc). Let's keep it here for the moment as it could be useful to refer to it. 

Github Issues on this repository should be for: issues, bugs, enhancements, new features, questions and practical tasks..

**Comment by bertspaan** [comment]
@timwaters: NYPL’s Map Warper has an (undocumented?) API for downloading masks: http://maps.nypl.org/shared/masks/15737.gml. Will this be included in new version?
