### ISSUE TITLE
Map card design

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#66]
Here is a map card design proposal. I have added features that are needed to accommodate layer reordering that was suggested by Ari in the demo.

The size of the card can be slightly larger without affecting the functionality too much. Here the map image is 70x70 px, it could be 80x80, and the buttons to the right could be 40x40. Current measures are based on iD design.
# Basic state

![wikimaps-warper_basic](https://cloud.githubusercontent.com/assets/4725416/12373426/c7c18eb8-bc81-11e5-8560-43b3b208d18f.png)
# Expanded metadata view

![wikimaps-warper_expanded](https://cloud.githubusercontent.com/assets/4725416/12373548/53c246e8-bc85-11e5-91f6-a204ce55f596.png)
# Flyout for actions

![wikimaps-warper_flyout](https://cloud.githubusercontent.com/assets/4725416/12373427/c7c2fa0a-bc81-11e5-8697-44b94cef400c.png)
# Reorder - hover over middle area

![wikimaps-warper_reorder](https://cloud.githubusercontent.com/assets/4725416/12373430/c7c4092c-bc81-11e5-8de7-54cca5afb639.png)
# Remove map from list

![wikimaps-warper_close](https://cloud.githubusercontent.com/assets/4725416/12373425/c7c00c82-bc81-11e5-903c-d95c0a31e00e.png)
# Drag maps to reorder

![wikimaps-warper_reorder2](https://cloud.githubusercontent.com/assets/4725416/12373428/c7c3c70a-bc81-11e5-8034-99f93d91a972.png)
# Change map transparency

![wikimaps-warper_transparency](https://cloud.githubusercontent.com/assets/4725416/12373432/c7da671c-bc81-11e5-9248-0394e297e890.png)
# Map transparency display

![wikimaps-warper_transparency3](https://cloud.githubusercontent.com/assets/4725416/12373433/c7de17f4-bc81-11e5-861e-4a4e9d226373.png)
# Map transparency display on hover

![wikimaps-warper_transparency2](https://cloud.githubusercontent.com/assets/4725416/12373431/c7da709a-bc81-11e5-9930-ac11580d8886.png)

**Comment by timwaters** [comment]
Great set of mockups, I believe they should now be in the external front end project: https://github.com/wikimaps-dev/wikimaps-html

The mapwarper code (and thus, these issues) should be just for the existing user interface and site and the future API only proposal. mapwarper will be the API for this external project to talk to, but mapwarper won't be running these new designs, if that makes sense :)

Similar to how iD has it's own project and the openstreetmap website has it's own one also, if that helps.

I'll close this for now.
