### ISSUE TITLE
Develop static layout in HTML

### ISSUE THREAD

**Issue by timwaters** [wikimaps-dev/mapwarper#8]

**Comment by susannaanas** [comment]
Check out wireframes for flows
https://docs.google.com/presentation/d/10ICyB7rHzuQ02QGl65Zcl6I124Mb4HI9ImGjeoa3_xo/edit#slide=id.g55507fafd_0398

**Comment by timwaters** [comment]
Closing this as the plan now is for mapwarper to just act as an API. 
The front end would be in another project
