### ISSUE TITLE
New wikimaps call has wrong redirect for warped maps

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#98]
Map template button for a readily georeferenced map calls a page tab by the name #Preview_map_tab but the correct name is #Preview_tab

**Comment by timwaters** [comment]
Is this the new Map template or the old version? Is this a bug in the warper?

**Comment by susannaanas** [comment]
This seems to me to be on the Warper side, since the string does not exist
in the template, and I recall the operation to direct to different subpages
takes place there. This is the existing Warper. It does no harm really,
since there is fallback to the front page, but a feature is missing.

2016-05-25 15:04 GMT+03:00 Tim Waters notifications@github.com:

**Comment by timwaters** [comment]
I have some confusion @susannaanas could you give a link or screenshot showing the button with the link, and/or maybe the steps that is taken to reproduce the bug. Thanks :)

**Comment by timwaters** [comment]
Ahh! I think I understand the steps!

The link from the template is to /new?pageid=123 and if the warper finds it, and the map is warped, it redirects and tries to load the preview (warped) page, but the link is wrong. 

Okay I understand this bug now, and can assign this to myself.

**Comment by timwaters** [comment]
wikimaps_controller line 47 or so 
redirect_to map_path(id: map, anchor: 'Preview_Map_tab')

**Comment by susannaanas** [comment]
Great! It seems you got it right!

2016-05-26 0:10 GMT+03:00 Tim Waters notifications@github.com:

**Comment by timwaters** [comment]
okay, fixed in 256fbd0
